### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by dowadidi** [verbb/gift-voucher#10]
### Description
The voucher codes are no longer being generated when an order is complete. The voucher pdf is blank, and purchased vouchers do not appear in the backend.

### Steps to reproduce

1. Add a voucher to your cart.
2. Checkout.

### Additional info

- Plugin version: 2.0.4
- Craft version: Craft Pro 3.0.34
- Commerce version: 2.0.0-beta.14

**Comment by engram-design** [comment]
Are you able to provide any additional information to help with this? I've tried a few different methods during checkout, and its working as expected.

Are you using set-price vouchers, or user-provided ones?

Was the total for your order greater than $0?

Happy to chat on the Craft Slack (handle @crawf).
