### ISSUE TITLE
Cannot assign null to property verbb\giftvoucher\events\PdfEvent::$order of type craft\commerce\elements\Order 

### ISSUE THREAD

**Issue by CMeldgaard** [verbb/gift-voucher#101]
### Describe the bug

When trying to genereate a PDF for a voucher generated from the backend, the system fails as it expects the $order property to be an Order element and not null

### Steps to reproduce

1. Generate code in backend
2. Push "Download PDF"

### Craft CMS version

4.3.1

### Plugin version

3.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.4](https://github.com/verbb/gift-voucher/releases/tag/3.0.4)
