### ISSUE TITLE
Can't delete Vouchers or Codes

### ISSUE THREAD

**Issue by CMeldgaard** [verbb/gift-voucher#107]
### Describe the bug

It's not possible to delte voucher and codes from the admin element index

![image](https://user-images.githubusercontent.com/14794642/204150568-7c3dc980-b97c-4671-ae89-2dcb51daf5b1.png)
![image](https://user-images.githubusercontent.com/14794642/204150585-b1a53eef-c02e-4917-b07e-5be33edf5e7b.png)

### Steps to reproduce

1. Create Voucher/Code
2. Mark it in the element index
3. Go to menu, where delete is "grayed" out

### Craft CMS version

4.3.3

### Plugin version

dev-craft-4 as 3.0.4. (also happens in "plain" 3.0.4)

**Comment by engram-design** [comment]
Fixed in [3.0.5](https://github.com/verbb/gift-voucher/releases/tag/3.0.5)
