### ISSUE TITLE
Return errors in CartController::addCode in ajax requests

### ISSUE THREAD

**Issue by Anubarak** [verbb/gift-voucher#11]
### Description
Curerntly when someone enters a wrong Code that doesn't exist or can't be found anywhere via ajax there are no errors returned - you just receive the blank page. Could you eventually include errors in your Response and not just return `null`?

### Steps to reproduce

1. Create a [Redeeming Voucher Code Form](https://verbb.io/craft-plugins/gift-voucher/docs/template-guides/redeeming-voucher-codes)
2. Insert a wrong Code
3. Submit the form via Ajax
4. Receive a blank page since Craft will route it wrong because `null` is returned instead of a `yii\web\Response` in the controller

### Steps to solve
Change this 
```PHP
if ($error) {
    // Check to see if its a Coupon code
    $isCouponCode = Commerce::getInstance()->getDiscounts()->getDiscountByCode($voucherCode);

    if ($isCouponCode) {
        $couponError = '';

        // Try and apply the coupon code
        $this->_cart->couponCode = $voucherCode;
        $couponCode = Commerce::getInstance()->getDiscounts()->orderCouponAvailable($this->_cart, $couponError);

        if ($couponError) {
            $this->_cart->addErrors(['couponCode' => $couponError]);
            return null;
        }

        return $this->_returnCart();
    }

    $this->_cart->addErrors(['voucherCode' => $error]);
    return null;
}
```

And add these lines in order to return JSON instead of nothing.. Otherwise I would need to create a second route or an event but I would like to avoid that
```PHP
if($request->getAcceptsJson() === true){
    $error = Craft::t('gift-voucher', 'No Code found');

    if ($request->getAcceptsJson()) {
        return $this->asJson(['error' => $error, $this->_cartVariable => $this->cartArray($this->_cart)]);
    }
}

return null;
```

**Comment by engram-design** [comment]
Updated in [2.0.5](https://github.com/verbb/gift-voucher/releases/tag/2.0.5)
