### ISSUE TITLE
Voucher plugin with commerce 4 lite not working?

### ISSUE THREAD

**Issue by kevinmu17** [verbb/gift-voucher#117]
### Question

Does the plugin work with commerce lite? i'm not quite sure and there are no errors when trying to redeem a code, but somehow it's not working.

### Additional context

using the docs form [redeeming voucher codes](https://verbb.io/craft-plugins/gift-voucher/docs/template-guides/redeeming-voucher-codes#redeeming-voucher-codes)

**Comment by engram-design** [comment]
That's correct, Gift Voucher requires Commerce Pro which is stated in [several](https://verbb.io/craft-plugins/gift-voucher/features) [places](https://verbb.io/craft-plugins/gift-voucher/docs/get-started/requirements).

**Comment by kevinmu17** [comment]
ah! thanks, the former i didn't see, straight went to the requirement docs. 
The reason I asked was because the sentence `Gift Voucher requires Craft Commerce 4.0 or greater (Pro edition).` wasn't that clear to me. docs suggestion: `Gift Voucher requires Craft Commerce Pro 4.0 or greater.` reads clearer imo.
