### ISSUE TITLE
Voucher applied multiple times to same order

### ISSUE THREAD

**Issue by CMeldgaard** [verbb/gift-voucher#119]
### Describe the bug

On two seperate sites, we have experienced that a giftvoucher gets applied multiple time to the same order, resulting in the customer paying to little.

![image](https://github.com/verbb/gift-voucher/assets/14794642/4d8f8ac9-f5cf-44af-961c-742db304e3f9)

### Steps to reproduce

Haven't been able to reproduce it manually

### Craft CMS version

4.4.7.1

### Plugin version

3.0.7

**Comment by engram-design** [comment]
I'll need to know a few settings for your store, as this doesn't happen (for me) on a default, simple install.

- How many items in the cart?
- Any other adjusters applied, like discounts, tax or shipping?
    - If shipping or tax, their respective categories would be good to know

You mention not being able to reproduce it manually, so this only seems to effect some orders? If that's correct, is there anything different about an order this has occurred on, and one where it hasn't?
