### ISSUE TITLE
Propagation to new sites triggered even if Types are not setup

### ISSUE THREAD

**Issue by pixelmachine** [verbb/gift-voucher#120]
### Describe the bug

When you add a new site to a multi-site install, vouchers seem to be automatically propagated to the new site. However when adding a new site it looks like only the first Voucher Type is setup automatically, leading to failed propagation for all other types. I think that's correct.

Log:
```
Resaving elements
Status: Failed
Error: Voucher's type (4) is not enabled for site 6

{
  "description": null,
  "elementType": "verbb\\giftvoucher\\elements\\Voucher"
  "criteria":
  {
    "siteld": 1,
    "status": null,
    "enabledForSite": false
  }.
  "updateSearchIndex": false,
  "set": null,
  "to": null,
  "ifEmpty": false,
  "touch": false
}
```

I guess either they should just not be propagated or all the Types should be cloned like the first one is.

### Steps to reproduce

1. Add a new site to an existing site with multiple voucher types
2. Check your queue to see failed propagation 
3. Check voucher types and see that only the first has cloned the existing settings

### Craft CMS version

3.9.4

### Plugin version

2.7.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [2.7.4](https://github.com/verbb/gift-voucher/releases/tag/2.7.4)
