### ISSUE TITLE
Cannot assign craft\console\Request to property verbb\giftvoucher\storage\Session::$request of type ?craft\web\Request

### ISSUE THREAD

**Issue by mcjackson18** [verbb/gift-voucher#125]
### Describe the bug

We've developed a product subscriptions plugin that creates orders using a console command (the orders are automatically processed each night using a cronjob). When we try to run the console command it errors with the following message:

Exception 'TypeError' with message 'Cannot assign craft\console\Request to property verbb\giftvoucher\storage\Session::$request of type ?craft\web\Request'

in /var/www/html/vendor/verbb/gift-voucher/src/storage/Session.php:33

### Steps to reproduce

1. Create a new order via a console command.

### Craft CMS version

Craft Pro 4.9.3

### Plugin version

3.0.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.12"`.

**Comment by mcjackson18** [comment]
Hi @engram-design, thanks for the update.

Sorry it's taken me a while to get round to testing this, now when I try to create an order from the console I'm getting the following error:

`Exception 'craft\errors\MissingComponentException' with message 'Session does not exist in a console request.'
`
```
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/Session.php(94): craft\console\Application->getSession()
#1 /var/www/html/vendor/craftcms/cms/src/helpers/Session.php(109): craft\helpers\Session::session()
#2 /var/www/html/vendor/verbb/gift-voucher/src/storage/Session.php(97): craft\helpers\Session::exists()
#3 /var/www/html/vendor/verbb/gift-voucher/src/adjusters/GiftVoucherAdjuster.php(45): verbb\giftvoucher\storage\Session->getCodeKeys(Object(craft\commerce\elements\Order))
#4 /var/www/html/vendor/craftcms/commerce/src/elements/Order.php(1956): verbb\giftvoucher\adjusters\GiftVoucherAdjuster->adjust(Object(craft\commerce\elements\Order))
```

Thanks

**Comment by engram-design** [comment]
All good, just pushed up some more fixes for that. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.12"`.

**Comment by mcjackson18** [comment]
@engram-design, thanks for the quick update - that fixed it :thumbsup:.
