### ISSUE TITLE
Ensure PDF URL matches site

### ISSUE THREAD

**Issue by jamiegrisdale** [verbb/gift-voucher#126]
### What are you trying to do?

The `getPdfUrl` and `getPdfUrlForCode` functions use `currentSite` to form the URL but this means that URLs via queued emails will likely link to the default site on a multisite setup.

### What's your proposed solution?

Since you already have the Order why not use the `orderSite` object instead to ensure whatever triggers the email, the correct context is maintained.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.12"`.

**Comment by engram-design** [comment]
Updated in [3.0.13](https://github.com/verbb/gift-voucher/releases/tag/3.0.13)
