### ISSUE TITLE
Error when installing Craft with existing project config

### ISSUE THREAD

**Issue by white-lukas** [verbb/gift-voucher#128]
### Describe the bug

When installing Craft with an existing Project config, 
The installation fails because the `$event->oldPrimarySiteId` is `null` when this event is handled
https://github.com/verbb/gift-voucher/blob/craft-5/src/services/VoucherTypes.php#L434C68-L434C84
After commenting [this](https://github.com/verbb/gift-voucher/blob/craft-5/src/GiftVoucher.php#L184) line the install completes successfully

### Steps to reproduce

1. Have an existing project config
2. start with a clean DB
3. Go to the craft install process
4. Install failes

### Craft CMS version

5.2.5

### Plugin version

dev-craft-5 as 4.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [4.0.1](https://github.com/verbb/gift-voucher/releases/tag/4.0.1)
