### ISSUE TITLE
Unable to generate catalog pricing

### ISSUE THREAD

**Issue by white-lukas** [verbb/gift-voucher#129]
### Describe the bug

When creating a pricing rule with a purchasable condition, the generation of catalog pricing is failing on: https://github.com/craftcms/commerce/blob/5.x/src/elements/conditions/purchasables/PurchasableConditionRule.php#L63
`$this->_elementIds` is an empty string
```json
{"craft\\commerce\\elements\\Variant":["106778"],"verbb\\giftvoucher\\elements\\Voucher":""}
```

### Steps to reproduce

1. create a pricing rule
2. add a purchasable condition
3. select a variant and no voucher
4. queue job failes

### Craft CMS version

5.2.7

### Plugin version

4.0.1

### Multi-site?

yes

**Comment by engram-design** [comment]
I don't believe this is a Gift Voucher issue. Disabling the Gift Voucher plugin and just saving the pricing rule with no Purchasables selected produces the same error.

<img width="867" alt="image" src="https://github.com/user-attachments/assets/a8a6540b-2c94-4332-9182-f8bdcced6a1a">

I would file this as an issue with Commerce.

**Comment by white-lukas** [comment]
Yeah but it's logic that when you select this condition, that the field is then required, so craft might need to make it required.

But this means that it's impossible to make a pricing rule without selecting a gift voucher!
