### ISSUE TITLE
product variable not present in preview template

### ISSUE THREAD

**Issue by TheRealOverheal** [verbb/gift-voucher#133]
### Describe the bug

Hi!
There is no 'product' variable passed to the template when rendering a preview for a voucher.

To be consistent with the docs, the voucher should always be accessable via the product variable in the template.

### Steps to reproduce

1. make a voucher
2. click preview
3. product variable is null

### Craft CMS version

4.10.3

### Plugin version

3.0.12

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.13"`.

**Comment by engram-design** [comment]
Fixed in [3.0.14](https://github.com/verbb/gift-voucher/releases/tag/3.0.14)
