### ISSUE TITLE
Duplicating a voucher not possible, integrity constrain violation

### ISSUE THREAD

**Issue by Nellyaa** [verbb/gift-voucher#134]
### Describe the bug

Duplicating a voucher, either from the element index or from the save menu "Save as a new gift voucher" is not possible. It happens with enabled and disabled vouchers alike.

The following error occurs:

`[HTTP 500 – Internal Server Error](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#500) – [yii\web\ServerErrorHttpException](https://www.yiiframework.com/doc-2.0/yii-web-servererrorhttpexception.html)
An error occurred when duplicating the voucher.
↵
Caused by: Integrity constraint violation – [yii\db\IntegrityException](https://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html)
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'V001-01' for key 'idx_rgtfozjpiyufwrmiwxaisenekdwrfjlpclii'
The SQL being executed was: INSERT INTO `giftvoucher_vouchers` (`id`, `postDate`, `expiryDate`, `typeId`, `promotable`, `availableForPurchase`, `taxCategoryId`, `shippingCategoryId`, `price`, `customAmount`, `sku`, `dateCreated`, `dateUpdated`, `uid`) VALUES (481609, '2024-08-12 08:51:00', NULL, 1, 0, 1, 1, 2, '5', 0, 'V001-01', '2024-08-13 17:16:30', '2024-08-13 17:16:30', '9bf72d3a-3f20-48dd-952a-0dcd67de2e23')
in /var/www/XXXXXXXXXXXXXXXX/releases/20240813085833/vendor/yiisoft/yii2/db/Schema.php at line 676

Error Info: Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry 'V001-01' for key 'idx_rgtfozjpiyufwrmiwxaisenekdwrfjlpclii'
)
↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'V001-01' for key 'idx_rgtfozjpiyufwrmiwxaisenekdwrfjlpclii'
in /var/www/XXXXXXXXXX/releases/20240813085833/vendor/yiisoft/yii2/db/Command.php at line 1320`

### Steps to reproduce

EITHER

1. Open voucher edit page
2. Click the submenu on the save menu and select "Save as a new gift voucher"
3. Get integrity constrain violation 500 error

OR

1. Select one voucher from the element index
2. Open the cog menu
3. Click "Duplicate"

### Craft CMS version

4.10.3

### Plugin version

3.0.12

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.13"`.

**Comment by engram-design** [comment]
Fixed in [3.0.14](https://github.com/verbb/gift-voucher/releases/tag/3.0.14)
