### ISSUE TITLE
PDF's ignoring paper size / orientation

### ISSUE THREAD

**Issue by Tam** [verbb/gift-voucher#14]
### Description
The generated PDFs are ignoring the paper size / orientation set in commerce (it would also be nice to manage these options in Gift Vouchers, separately from Commerce).

Additionally, the `attach` and `format` params for the PDF download link have no effect.

### Steps to reproduce

1. Set the paper size / orientations to something other than the defaults (i.e. 'a4', 'landscape').
2. Download a PDF voucher.

### Additional info

- Plugin version: 2.0.6
- Craft version: Craft Pro 3.0.35

**Comment by engram-design** [comment]
Fixed on all counts in [2.0.7](https://github.com/verbb/gift-voucher/releases/tag/2.0.7)
