### ISSUE TITLE
Translate the adjuster description

### ISSUE THREAD

**Issue by Anubarak** [verbb/gift-voucher#15]
### Description
It would be really nice to gain the ability to translate the adjuster description for the frontend. When the cart is not saved -> no snapshot is created there is no way to receive the code itself so all we can do is to strip the code from the existing description via regex but as soon as you change it we'll have a problem. 

Something like
```PHP
$adjustment->description = Craft::t('gift-voucher', 'Gift Voucher discount using code {code}', [ 
    'code' => $voucherCode->codeKey;
]);
```

So we can use a custom static translation to change it the way we like

**Comment by TomDeSmet** [comment]
I have tried to translate this, but I can't seem to get it to work?

Am I wrong in assuming that I need to create a `gift-voucher.php` file inside the `translations/nl` folder and than add this line of code: `"Gift Voucher discount using code {code}" => "Geschenkbon met code {code}"`?

**Comment by engram-design** [comment]
That's correct - can you translate anything else about Gift Voucher? Maybe even have a look at some of the strings used in the control panel (on any Gift Voucher screen), and override them, just to test?

**Comment by TomDeSmet** [comment]
No, can't translate anything.
Besides, I noticed there isn't a translations folder in the plugin directory either. Shouldn't that take care of the CP translations instead of the translation files in my project? But I tried both. I tried everything I know about translations :)

**Comment by engram-design** [comment]
There doesn't need to be a translations folder in the plugin itself - unless the plugin supports multiple languages out of the box. Gift Voucher is only provided in English for the time being. Even if there was, you can totally override it on your specific project.

So if it's not overriding any strings, it sound like something else might be going on. Can you override anything in a `site.php` or `app.php` file - that would be for Craft?

**Comment by TomDeSmet** [comment]
My whole site is translated with a site.php so that definitely works.

**Comment by engram-design** [comment]
Strange, so I placed a file `translations/en-AU/gift-voucher.php` with the content:

```
<?php

return [
    "Gift Voucher discount using code {code}" => "Geschenkbon met code {code}",
];
```

and the result looks correct - https://d.pr/i/BJU6Tx

**Comment by TomDeSmet** [comment]
I copy/pasted this line in my translation file and I saw no difference whatsoever, but it did translate it now.
Very strange. Maybe I had an invisible character somewhere in my text? Or some strange caching issue...

Thanks for the help! Solved!
