### ISSUE TITLE
Error generating PDF due to missing 'order' variable

### ISSUE THREAD

**Issue by paulgoodfield** [verbb/gift-voucher#17]
### Description

Generating PDF of Voucher Code fails because **order** variable isn't available to PDF template

### Steps to reproduce

1. After creating a voucher code for an order, click on **Download PDF** button when viewing Voucher Code in control panel.
2. Generated PDF simply displays the text **An error occurred while generating this PDF.** If I remove any references to the **order** variable in the PDF template, it generates the PDF correctly.

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.36

**Comment by engram-design** [comment]
I'll assume you've created this voucher code manually in the control panel, by going to Voucher Codes > New code? As such, that's correct - there's no order associated with this voucher code, because you've manually created it as a standalone code. This can be useful if you as a store owner want to issue a customer with a voucher, for a variety of reasons.

You'll need to have conditionals in your templates to check if there's an order variable available to you. Refer to https://verbb.io/craft-plugins/gift-voucher/docs/template-guides/pdf-template#example-template

**Comment by paulgoodfield** [comment]
@engram-design Thanks for getting back to me. I'm creating the voucher code programmatically from another module I've created. It seems to be linking to the orders correctly (when going to Gift Voucher > Voucher Codes in the Control Panel I can see that the Order column contains an order number for each code).

I noticed that in the PDF template example you have there is a conditional on line 101:

`{% if order and order.customer.user %}
    <div class="field-customer">Gifted by {{ order.customer.user.name }}</div>
 {% endif %}`

but line 89 also tries to use the order variable without any conditional. This was the line that was giving me an error:

`<span class="field-amount">{{ code.currentAmount | currency(order.currency, [], [], true) }}</span>`

**Comment by engram-design** [comment]
I just changed the template where this occurs shortly after responding to this ticket - that's my fault for not testing that case correctly!

Ah right - so the Order column shows the shorthand order number, but its still throwing that error? Can you look at the row in your `giftvoucher_codes` db table, and look for the `orderId` column to see if its a number, or null?

**Comment by paulgoodfield** [comment]
Strangely, I've just tested this again on a different machine using your original template code and it seems to be working ok. It looks like the codes I'm generating all do have an order id in the database, so it's all good. Thanks for looking to this!

**Comment by engram-design** [comment]
Sounds like its all good, so closing for now then!
