### ISSUE TITLE
Can't search by voucher code

### ISSUE THREAD

**Issue by Tam** [verbb/gift-voucher#21]
### Description
Searching by full or partial voucher code returns zero results.

### Steps to reproduce

1. Try searching by a voucher code in the Codes section

### Additional info

- Plugin version: 2.0.11
- Craft version: Pro 3.1.30

**Comment by engram-design** [comment]
This should be included in [2.0.12](https://github.com/verbb/gift-voucher/releases/tag/2.0.12).
