### ISSUE TITLE
Tax miscalculation

### ISSUE THREAD

**Issue by benrnorman** [verbb/gift-voucher#22]
Hi all,
Love the plugin, just one issue. I'm not sure if I'm doing this wrong or what.

### Description
After I apply a discount to an order, the tax is not reflected correctly using `{{ order.getAdjustmentsTotalByType('tax', true) }}`.

I have a 10% GST tax on all my products. It has the following settings:
- "Tax already included in taxable subject" is true.
- Taxable Subject is "Order total taxable price (Line item subtotal + Total discounts + Total shipping)"

If I add a $100 product to cart, my template (correctly) reads:
- Total: $100.00 (using `order.total`)
- Tax Included: $9.09 (using `order.getAdjustmentsTotalByType('tax', true)`)

If I add a Craft Commerce 10%-off coupon, it now (correctly) reads:
- Total: $90.00
- Tax Included: $8.18

But if I then add a $50 gift voucher, the included tax value does not change. It will read:
- Total: $40.00
- Tax Included: $8.18

### Steps to reproduce

1. Create a percentage tax with the above settings.
2. Create a gift voucher.
3. Apply voucher to cart with line items and see output of `order.getAdjustmentsTotalByType('tax', true)`.

### Additional info

- Plugin version: 2.0.11
- Craft version: 3.2.3
- Commerce version: 2.1.10

**Comment by engram-design** [comment]
Yep, this is a bug, and am investigating. Also looking to add more options to control how tax works in relation to a voucher.

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/gift-voucher/releases/tag/2.1.0)
