### ISSUE TITLE
Cant change site when editing a voucher

### ISSUE THREAD

**Issue by dannylewin** [verbb/gift-voucher#25]
### Description

It wont allow you to change the site when editing a voucher. It redirects to the main index (showing the selected site in the drop-down), but then shows the default site again when you click in to a voucher.

### Steps to reproduce

1. Click in to a voucher to edit
2. Try to change the site
3. You get redirected back to the index page

### Additional info

- Plugin version: Current
- Craft version: Current

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/gift-voucher/releases/tag/2.1.0)
