### ISSUE TITLE
Ability to assign voucher to an existing user

### ISSUE THREAD

**Issue by engram-design** [verbb/gift-voucher#26]

**Comment by Anubarak** [comment]
For what it's worth: I kinda implemented that already in my fork

https://github.com/Anubarak/gift-voucher/commit/9f2f6dfc2764bf13bfccb92977b6b3b698ff4275

This would solve https://github.com/verbb/gift-voucher/issues/28 as well or at least make preparations for being fixed.

I implemented an additional component `codeStorage` that will handle adding and removing codes for a user. There are currently two possible types of classes for this, first the session (your default session handler) and besides that a way to store codes in an orders field layout in a custom `Codes` relation field. That way admins can just include the code in the field layout for customers and it's done

**Comment by engram-design** [comment]
Thanks @Anubarak still need to fully dive into the fork, but thanks!

**Comment by engram-design** [comment]
Thanks again for your work here, just have a few adjustments to make, but merged into [2.1.0](https://github.com/verbb/gift-voucher/releases/tag/2.1.0)
