### ISSUE TITLE
Control when tax is applied for applied voucher codes

### ISSUE THREAD

**Issue by jmauzyk** [verbb/gift-voucher#29]
### Description

I noticed with the update to 2.1.0, voucher discounts are now applied before tax. This makes sense if codes are provided as a promotional discount or similar. However, in situations where vouchers are being sold as e-gift cards, the old method of applying the discount after taxes is correct, as gift cards should be sold tax-free and then tax collected when the gift card is redeemed (at least in the US).

Would it be possible to add a configuration setting for vouchers or voucher types that allows admins to select whether codes of that type are applied before or after taxes have been calculated?

### Additional info

- Plugin version: 2.1.0
- Craft version: 3.3.19

**Comment by engram-design** [comment]
Didn't realise this was a thing! Added in [2.1.1](https://github.com/verbb/gift-voucher/releases/tag/2.1.1)

**Comment by jmauzyk** [comment]
@engram-design Thanks for the quick turnaround on this! However, it wasn't working for me. I believe line 218 of GiftVoucher.php needs to be:
`$event->types[] = GiftVoucherAdjuster::class;`

**Comment by engram-design** [comment]
Oh dear, late night (early morning) commit! Fixed in [2.1.2](https://github.com/verbb/gift-voucher/releases/tag/2.1.2)
