### ISSUE TITLE
FR - PDF download link in codes in the dashboard

### ISSUE THREAD

**Issue by billythekid** [verbb/gift-voucher#3]
If a voucher code is created in the admin panel (or when viewing any voucher codes) and pdf is enabled it would be nice to have a 'download voucher pdf' button just like when viewing an order itself.

I'm thinking of the case of tying in-store voucher creation by staff members for customers visiting the store. They could print it out in-store and hand it to the customer, who can then use it online or instore or whatever. Saves having to go through the cart process for staff who just want to spawn a voucher that's been paid for in-store. They can do the spawning already, just can't print it out for the customer, they'd need to write it down on a gift card or, god forbid, copy the code to a word template or something! lol

**Comment by engram-design** [comment]
Added in [2.0.3](https://github.com/verbb/gift-voucher/releases/tag/2.0.3)
