### ISSUE TITLE
Created Date in Element Index shows Element Created date rather than voucher

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/gift-voucher#33]
This is extremely niche so may not be worth bothering with. It has only arisen because I'm importing vouchers from an old EE site using Espresso Store 

The Created Date shown in the voucher element index appears to be taken from the row in the elements table rather than the dateCreated value from the voucher table

Should it not show the value from the voucher table?

- Plugin version: 2.2.1
- Craft version: 3.4.9

**Comment by engram-design** [comment]
Hmm, so they should probably be the same in practice. I assume you wrote your own importer? As vouchers are elements, the voucher record and the element record for the voucher should be pretty much in sync, and they are when creating vouchers 'normally'.

I can add this in, but I'd almost recommend updating your element records to mirror your voucher records

**Comment by peteeveleigh** [comment]
Yes I wrote a couple of SQL queries to migrate the codes and amounts from the Espresso Store tables.

I’ve redone my queries  to set the element dateCreated to the date the voucher was created - that makes more sense. I was just concerned about elements being “out of sequence” as it were but I don’t suppose that is really going to matter in the long run.

In case they are of use to anyone (there are a couple of 'magic numbers' in there for field layout etc but they're easily repurposed:

```
# Query 1 Get all giftcards created from 1st Dec 2018

# Remove stored function
DROP FUNCTION IF EXISTS createGiftCardElement;

# Stored procedure to create a giftcard element
DELIMITER $$
CREATE FUNCTION createGiftCardElement(
	created_date DATETIME
) RETURNS INT
BEGIN
	DECLARE lastElementId INT;
	SET lastElementId = 0;
	SET @thisTime = created_date;
	INSERT INTO elements VALUES(null,null,null,34,'verbb\\giftvoucher\\elements\\Code',1,0,@thisTime,@thisTime,null,UUID());
	SELECT LAST_INSERT_ID() INTO lastElementId;
	INSERT INTO elements_sites VALUES(null,lastElementId,1,null,null,1,@thisTime,@thisTime,UUID());
	INSERT INTO content(`id`,`elementId`,`siteId`,`title`,`dateCreated`,`dateUpdated`,`uid`) VALUES(null,lastElementId,1,null,@thisTime,@thisTime,UUID());
	RETURN lastElementId;
END$$
DELIMITER ;

# Insert a giftcard into new giftcards table
INSERT INTO giftvoucher_codes (
	id,
	voucherId,
	orderId,
	lineItemId,
	codeKey,
	originalAmount,
	currentAmount,
	expiryDate,
	dateCreated,
	dateUpdated,
	uid
)
SELECT
	createGiftCardElement(),
	7461,
	null,
	null,
	gc.code,
	gc.initial_value,
	gc.initial_value,
	expiry_date,
	created_date,
	created_date,
	UUID()
FROM exp_store_giftcard gc
WHERE created_date > '2018-12-01 00:00:00'
GROUP BY gc.code
ORDER BY created_date asc


#########################################################



# QUERY 2 update voucher balance

DROP FUNCTION IF EXISTS voucherSpend;


DELIMITER $$
CREATE FUNCTION voucherSpend(
	codeKey VARCHAR(255)
)
RETURNS DECIMAL(12,2)
BEGIN
	DECLARE spend DECIMAL(12,2);
	SET spend = 0;

	SELECT
	SUM(esgt.amount) into spend
	FROM exp_store_giftcard esg
	RIGHT JOIN exp_store_giftcard_transactions esgt ON esgt.giftcard_id = esg.id
	WHERE esg.code = codeKey AND esg.created_date > '2018-12-01 00:00:00'
	and void_date IS NULL
	GROUP BY esg.id;

	RETURN spend;
END$$
DELIMITER ;


UPDATE giftvoucher_codes gvc
SET gvc.currentAmount = gvc.originalAmount - voucherSpend(gvc.codeKey)

```
