### ISSUE TITLE
Project Config Support

### ISSUE THREAD

**Issue by BrandonJamesBorders** [verbb/gift-voucher#36]
### Description
Project Config Not Syncing

### Steps to reproduce

1. Add field to voucher type.
2. Observe no changes to project.yaml

### Additional info

- Plugin version: 2.2.4
- Craft version: 3.4.17.1

**Comment by engram-design** [comment]
Added in [2.3.0](https://github.com/verbb/gift-voucher/releases/tag/2.3.0)
