### ISSUE TITLE
How to use custom field in Voucher Code Field layout

### ISSUE THREAD

**Issue by john-henry** [verbb/gift-voucher#39]
### Description

I have included a plain text field which will be a message the user can add to a gift voucher.

This was added in _Gift Voucher > Settings > Voucher Code Field Layout_

How do I add this to the voucher template? What's the syntax for name attribute?

Then how do I show this field on the PDF/Order page etc? What's the syntax for templates there?

### Additional info

- Plugin version: 2.3.0
- Craft version: 3.4.23

**Comment by engram-design** [comment]
Looks like I've plain forgot to write docs for this, as introduced in this PR https://github.com/verbb/gift-voucher/pull/18. Sorry about that, I'll get to that tomorrow.

In the meantime, you need to store all field data as [line item options](https://docs.craftcms.com/commerce/v3/adding-to-and-updating-the-cart.html#line-item-options-and-notes), using your field handles, so:

```
<input type="text" name="options[myFieldhandle]" value="Some Value">
```

Once you've completed checkout, the values in your line item options will be mapped to your resulting Code elements.

Its for a different plugin, but I believe the process is similar to [Events](https://verbb.io/craft-plugins/events/docs/template-guides/single-event#line-item-options).

I'll need to review and get back to you with full docs...

**Comment by john-henry** [comment]
Brill Thanks Josh

**Comment by engram-design** [comment]
Refer to the updated docs:

https://verbb.io/craft-plugins/gift-voucher/docs/template-guides/single-voucher
https://verbb.io/craft-plugins/gift-voucher/docs/template-guides/pdf-template
