### ISSUE TITLE
Adding a voucher code consisting of whitespace redeems the latest voucher code

### ISSUE THREAD

**Issue by benface** [verbb/gift-voucher#4]
### Steps to reproduce

1. Create a voucher code with an amount via the CP
2. Use the `gift-voucher/cart/add-code` endpoint with a `voucherCode` of ` ` (a space)
3. Notice an adjustment has been added to the cart with the same amount as the voucher code you created, even if we didn't enter the right code

### Additional info

- Plugin version: 2.0.1
- Craft version: 3.0.28

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/gift-voucher/releases/tag/2.0.2)
