### ISSUE TITLE
Custom field value from Voucher layout does not populate with value after order completes

### ISSUE THREAD

**Issue by john-henry** [verbb/gift-voucher#41]
I added a custom field in Voucher settings called **voucherMessage**.

In the voucher form, I have

`<input type="text" name="options[voucherMessage]" value="">`

Once I pay and finish order, the value from that field does not populate back into the voucherMessage field for the code entry generated. It does appear in the order under options though.

Latest Craft and Gift Voucher plugin installed

**Comment by engram-design** [comment]
Sorry @john-henry this should be fixed in [2.4.0](https://github.com/verbb/gift-voucher/releases/tag/2.4.0)
