### ISSUE TITLE
saleAmount deprecation warning

### ISSUE THREAD

**Issue by jmauzyk** [verbb/gift-voucher#42]
### Description

Getting the following deprecation warning that appears to be triggered by line 512 of the Voucher element class when a gift voucher is purchased:

> The setting of “saleAmount” has been deprecated. “saleAmount” is automatically calculated

### Additional info

- Plugin version: 2.4.0
- Craft version: Pro 3.4.24, Commerce Pro 3.1.9

**Comment by engram-design** [comment]
Fixed in [2.4.1](https://github.com/verbb/gift-voucher/releases/tag/2.4.1)
