### ISSUE TITLE
Only receive generic error message when submitting by ajax

### ISSUE THREAD

**Issue by jmauzyk** [verbb/gift-voucher#43]
### Description

When applying a voucher code to a cart via a simple web form, it will return detailed error messages if an error occurs ("Voucher code is not valid," "Voucher code has no amount left," etc.). However, when applying vouchers to a cart via ajax, any errors return only a generic "Unable to update cart" message. Would it be possible to return more specific error messages by ajax as well?

### Additional info

- Plugin version: 2.4.0
- Craft version: Pro 3.4.24

**Comment by engram-design** [comment]
Full errors should be available in [2.4.1](https://github.com/verbb/gift-voucher/releases/tag/2.4.1)
