### ISSUE TITLE
Server error when trying to live preview vouchers

### ISSUE THREAD

**Issue by jmauzyk** [verbb/gift-voucher#44]
### Description

When trying to live preview vouchers, get the error message "A server error has occurred." Logs have the error message:
`2020-07-28 10:14:08 [-][10982][-][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Request contained an invalid body param in /home/parktool/parktoolweb2019/vendor/craftcms/cms/src/web/Request.php:719`

### Steps to reproduce

1. Open a voucher edit page in the CP.
2. Click _Live Preview_ button.

### Additional info

- Plugin version: 2.4.1
- Craft version: Pro 3.4.29.1

**Comment by engram-design** [comment]
Should be fixed in [2.4.2](https://github.com/verbb/gift-voucher/releases/tag/2.4.2)
