### ISSUE TITLE
Renaming fields not working

### ISSUE THREAD

**Issue by bavocorteville** [verbb/gift-voucher#47]
**Description**
Renamed labels are showing original label text.

**Steps to reproduce**
1. Go to Gift Voucher settings
2. Rename field label (Field Layout Designer view)
3. Check label of the field (Voucher Codes entry)

**Additional info**
- Plugin version: 2.4.3
- Craft version: Craft Pro 3.5.5
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Yep, Gift Voucher wasn't compatible with the 3.5+ field designer. See [2.5.0](https://github.com/verbb/gift-voucher/releases/tag/2.5.0)
