### ISSUE TITLE
Inserting * as code will return any possible Code available in the DB

### ISSUE THREAD

**Issue by Anubarak** [verbb/gift-voucher#49]
**Description**
Since you use Crafts internal `Db::parseParam` function in your CodeQuery to grab the code in [CodeService::matchCode](https://github.com/verbb/gift-voucher/blob/craft-3/src/services/CodesService.php#L228)
```php
    public function matchCode($codeKey, &$error)
    {
        $code = Code::findOne(['codeKey' => $codeKey]);
```
it will create a `LIKE %%` condition in the query.

So inserting `*` in an `addCode` request will return the last created Code. I would rate that as a heavy security issue.

**Steps to reproduce**
1. Install the plugin, create a code
2. create a form to add a code and insert `*`
3. see the cart will receive the last added code

**Comment by engram-design** [comment]
Well, crap. Thanks for reporting this. Should be fixed in [2.5.1](https://github.com/verbb/gift-voucher/releases/tag/2.5.1)
