### ISSUE TITLE
Variable is missing `getPdfUrl()` and `getOrderPdfUrl()`

### ISSUE THREAD

**Issue by benface** [verbb/gift-voucher#5]
### Description

In the Craft 3 version of the plugin, the `craft.giftVoucher` variable is missing the [documented](https://verbb.io/craft-plugins/gift-voucher/docs/template-guide/pdf-template) `getPdfUrl()` and `getOrderPdfUrl()` functions. There is a `getPdfUrl()` function on the `Voucher` element, but it is awkward to use, as you can see from my code:
```
order.lineItems[0].purchasable.getPdfUrl(order.lineItems[0])
```

In addition to not being global, why does it take a `$lineItem` argument when all it needs is the order?

I wish I could simply do this instead:

```
craft.giftVoucher.getOrderPdfUrl(order)
```

### Additional info

- Plugin version: 2.0.1
- Craft version: 3.0.28

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/gift-voucher/releases/tag/2.0.2)
