### ISSUE TITLE
Having a Supertable Field in a Voucher produces a massive amount of duplicates

### ISSUE THREAD

**Issue by Anubarak** [verbb/gift-voucher#50]
**Description**
When a Gift Voucher contains a Super Table field, each lineItem save will produce an incredible amount of duplicates.
This is because in your Vouchers `getSnapshot` function you include `$this->getAttributes()`and this will add all field values to the snapshop.

Unfortunately the field value is a `SuperTableQuery` and Yii2 activates it's toArray()  function, that will run through every single property, by executing the query again and again and again.

Here is the stack trace that is called, when I throw an exception in your Query

> /var/www/myspa/dev/htdocs/vendor/verbb/super-table/src/elements/db/SuperTableBlockQuery.php:373
Stack trace:
#0 /var/www/myspa/dev/htdocs/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1326): verbb\supertable\elements\db\SuperTableBlockQuery->beforePrepare()
#1 /var/www/myspa/dev/htdocs/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#2 /var/www/myspa/dev/htdocs/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(verbb\supertable\elements\db\SuperTableBlockQuery))
#3 /var/www/myspa/dev/htdocs/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand(Object(craft\db\Connection))
#4 /var/www/myspa/dev/htdocs/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#5 /var/www/myspa/dev/htdocs/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1497): craft\db\Query->one(NULL)
#6 /var/www/myspa/dev/htdocs/vendor/verbb/super-table/src/elements/db/SuperTableBlockQuery.php(110): craft\elements\db\ElementQuery->one()
#7 /var/www/myspa/dev/htdocs/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): verbb\supertable\elements\db\SuperTableBlockQuery->__get('voucher')
#8 /var/www/myspa/dev/htdocs/vendor/yiisoft/yii2/helpers/BaseJson.php(165): craft\elements\db\ElementQuery->toArray()
#9 /var/www/myspa/dev/htdocs/vendor/yiisoft/yii2/helpers/BaseJson.php(184): yii\helpers\BaseJson::processData(Object(verbb\supertable\elements\db\SuperTableBlockQuery), Array, '5f745c0e09e074....')
#10 /var/www/myspa/dev/htdocs/vendor/yiisoft/yii2/helpers/BaseJson.php(61): yii\helpers\BaseJson::processData(Array, Array, '5f745c0e09e074....')
#11 /var/www/myspa/dev/htdocs/vendor/craftcms/cms/src/helpers/Db.php(121): yii\helpers\BaseJson::encode(Array)
#12 /var/www/myspa/dev/htdocs/vendor/craftcms/cms/src/db/ActiveRecord.php(126): craft\helpers\Db::prepareValueForDb(Array)
#13 /var/www/myspa/dev/htdocs/vendor/craftcms/cms/src/db/ActiveRecord.php(39): craft\db\ActiveRecord->_prepareValue('snapshot', Array)
#14 /var/www/myspa/dev/htdocs/vendor/craftcms/commerce/src/services/LineItems.php(262): craft\db\ActiveRecord->__set('snapshot', Array)
#15 /var/www/myspa/dev/htdocs/vendor/craftcms/commerce/src/elements/Order.php(3081): craft\commerce\services\LineItems->saveLineItem(Object(craft\commerce\models\LineItem), false)
#16 /var/www/myspa/dev/htdocs/vendor/craftcms/commerce/src/elements/Order.php(1939): craft\commerce\elements\Order->_saveLineItems()

**Steps to reproduce**
1. Create a Supertable or Matrix Field inside a Voucher
2. Try to save a cart with a voucher
3. see many multiple queries

**Steps to resolve that problem** 
- already pass `$this->getAttributes()` in your event and let me clean it
- even better: don't include queries in your snapshot... no one will ever be able to read it anyway since the query itself is in the snapshot

As of now, I fixed it via LineItem::EVENT_AFTER_POPULATE
```php
foreach ($lineItem->snapshot as $attribute => $value){
    if($value instanceof Query){
        unset($lineItem->snapshot[$attribute]);
    }
}
```
It reduced my query count from 2400 to 200

**Comment by engram-design** [comment]
Yep, oversight on my part trying to easily add all attributes. This now follows Commerce's lead of ensuring fields are opt-in. You can now also correctly modify this behaviour with `EVENT_AFTER_CAPTURE_VOUCHER_SNAPSHOT`, rather than the line item population event. See [docs](https://verbb.io/craft-plugins/gift-voucher/docs/developers/events#the-afterCaptureVoucherSnapshot-event)

See [2.5.2](https://github.com/verbb/gift-voucher/releases/tag/2.5.2)
