### ISSUE TITLE
Add Null option to CodeHelper::getCode

### ISSUE THREAD

**Issue by Anubarak** [verbb/gift-voucher#51]
**Description**
Your [Code](https://github.com/verbb/gift-voucher/blob/craft-3/src/helpers/CodeHelper.php#L18)
```php
    public static function getCode($code): Code
    {
        if (is_string($code) === true) {
            return Code::findOne(['codeKey' => $code]);
        }

        if (is_numeric($code)) {
            return Code::findOne($code);
        }

        if ($code instanceof Code) {
            return $code;
        }

        return null;
    }
``` 
will break if no Code is found because the function requires an object of type Code. If nothing is found there will be a fatal error.
Please add 
```PHP
public static function getCode($code): ?Code
```
to allow null or a Code

**Comment by engram-design** [comment]
You'll notice I removed this in https://github.com/verbb/gift-voucher/commit/0cbb421ea4e6f265ac051123efa2fb9e2ff9477a the reason being to keep a min PHP requirement of 7.0 (which is annoying anyway), to keep inline with Craft. Pretty sure nullable type hints are only supported in PHP 7.1+. This function was part of your original PR.

I've removed the type hint altogether for now in https://github.com/verbb/gift-voucher/commit/22293628d9891e4ec9cf414dbfba99352993d076
