### ISSUE TITLE
No error when entering an expired commerce discount code

### ISSUE THREAD

**Issue by Tam** [verbb/gift-voucher#52]
**Description**
If you enter a non-existent code the `voucherCode` error will return "Voucher code is not valid", but if you enter a discount code that is expired no error is returned.

**Steps to reproduce**
1. Create a discount code in commerce and set its end date in the past
2. Try to enter that code using the `gift-voucher/cart/add-code` action

**Additional info**
- Plugin version: 2.5.2
- Craft version: Pro 3.5.13.2
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
I'm not seeing this at all, which is odd. How are you displaying errors in your templates?

```
<form method="POST">
    <input type="hidden" name="action" value="gift-voucher/cart/add-code">
    {{ redirectInput('shop/cart') }}
    {{ csrfInput() }}

    <span class="{% if cart.getFirstError('voucherCode') %}has-error{% endif %}">
        <input type="text" name="voucherCode" width="11" class="{% if cart.getFirstError('voucherCode') %}has-error{% endif %}" placeholder="Voucher Code"/>
    </span>

    <input type="submit" class="button" value="Apply Voucher"/>
</form>
```

**Edit** I realised you mentioned **discount code** not voucher code, but that still works:

![screencapture-commerce3-test-shop-cart-2020-11-05-14_34_17](https://user-images.githubusercontent.com/1221575/98194678-0413b580-1f74-11eb-9b59-6f519c0e2fbd.png)

Just wanted to check you're checking for both `voucherCode` and `couponCode`:

```
{% if cart.getFirstError('voucherCode') %}
    <span class="flash">{{ cart.getFirstError('voucherCode') }}</span>
{% endif %}

{% if cart.getFirstError('couponCode') %}
    <span class="flash">{{ cart.getFirstError('couponCode') }}</span>
{% endif %}
```

**Comment by Tam** [comment]
Ah, I'm only checking for `voucherCode` errors, that'd be why! Thanks for the help!
