### ISSUE TITLE
Allow gift voucher PDF's to be attached to Commerce order confirmation emails

### ISSUE THREAD

**Issue by javangriff** [verbb/gift-voucher#53]
Currently it is possible to include a download link within the order confirmation email to allow users to download the gift voucher/s PDF, however, it would be great if the plugin also allowed the gift voucher PDF to also be attached to the email as well.

**Comment by engram-design** [comment]
Added in [2.5.3](https://github.com/verbb/gift-voucher/releases/tag/2.5.3).
