### ISSUE TITLE
Breaking error after upgrading Craft and Commerce

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/gift-voucher#54]
**Description**
Getting this error suddenly after upgrading to the latest Commerce and Craft.
When deleting all current orders/carts from the CP, it works again. But that is no option for a live site.

**UPDATE** After deleting allorders and carts, I tried to buy a voucher again and my previous voucher was still activated in the cart but not calculated as a discount and I'm unable to delete it.**

![Screen Shot 2020-11-06 at 12 04 25 PM](https://user-images.githubusercontent.com/16959207/98359295-48608d80-2028-11eb-9535-034b60aaea06.png)

**Additional info**
- Plugin version: 2.5.3
- Craft version: 3.5.15.1
- Multi-site: yes

**Comment by engram-design** [comment]
Are you calling `isVoucher` in your templates? This seems like an issue where the line item's purchasable "thing" doesn't exist anymore.

I can easily add a check in place, but wanted to check your usage first.

And removing a voucher is unfortunately not as easy as deleting the adjustment or order. It's stored in cache and applied to your order, which is a frustratingly over-complicated side effect of this PR https://github.com/verbb/gift-voucher/pull/18

**Comment by engram-design** [comment]
Have added a small guard for this. To get the fix early, change your `verbb/gift-voucher` requirement in `composer.json` to:

```
"require": {
  "verbb/gift-voucher": "dev-craft-3 as 2.5.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by TomDeSmet** [comment]
I have added this check everywhere that I use `isVoucher`: `item is defined and item and craft.giftVoucher.isVoucher(item)` but I still get the error. Is my check not correct?

I'll try your beta update next.

**Comment by TomDeSmet** [comment]
With the plugin update is works again.

**Comment by engram-design** [comment]
That's pretty strange, that check should be adequate. In any case, it's not a major change on my end. See [2.5.4](https://github.com/verbb/gift-voucher/releases/tag/2.5.4)
