### ISSUE TITLE
No vouchers in code storage for order

### ISSUE THREAD

**Issue by jerome2710** [verbb/gift-voucher#60]
**Description**
The plugin triggers an error for every completed order where no voucher code has been used. This seems undesirable, as the voucher codes (in our case) are optional. A log level like 'info' would be better suited here.

Please refer to: https://github.com/verbb/gift-voucher/blob/craft-3/src/services/CodesService.php#L122

**Additional info**
- Plugin version: 2.5.6
- Craft version: Craft Pro 3.5.17.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Yep, that certainly shouldn't be the case!

**Comment by jerome2710** [comment]
@engram-design I see you referenced a commit fixing this issue last week, thank you for your quick response. Could you release a new version of the plugin so we can update?

**Comment by engram-design** [comment]
Fixed in [2.5.7](https://github.com/verbb/gift-voucher/releases/tag/2.5.7)
