### ISSUE TITLE
Extend expirery to 36 months

### ISSUE THREAD

**Issue by CMeldgaard** [verbb/gift-voucher#72]
Can you extend the expirery date to 36 months, or make it possible to enter it manually. This is because in Denmark vouchers by law is valid for 3 years.

**Comment by engram-design** [comment]
No problem, updated in https://github.com/verbb/gift-voucher/commit/4b5dcf4477765a8d8f02eac3f0bdc4c6efa5f04b for the next release.

**Comment by engram-design** [comment]
Added in [2.6.3](https://github.com/verbb/gift-voucher/releases/tag/2.6.3)
