### ISSUE TITLE
Return value of verbb\giftvoucher\elements\Voucher::getPrice() must be of the type float, null returned

### ISSUE THREAD

**Issue by CMeldgaard** [verbb/gift-voucher#73]
**Description**
Im now getting the weirdest error. 
`Return value of verbb\giftvoucher\elements\Voucher::getPrice() must be of the type float, null returned`

in verbb​/gift-voucher​/src​/elements​/Voucher.php line 490.

It began after latest update that fixed the email problem, but i can't see anything in the commit that should affect this.

**Comment by CMeldgaard** [comment]
Hmm, the error appears when i in the voucher type i add an assets field, where the path the assets should be saved in includes {slug}. If i remove it from the url it works 🤔 .

**Comment by engram-design** [comment]
That seems bizarre behaviour, and I'm not sure how custom fields on the voucher type would affect this.

**Comment by engram-design** [comment]
Fixed in [2.7.0](https://github.com/verbb/gift-voucher/releases/tag/2.7.0)
