### ISSUE TITLE
Redemptions not working / appearing

### ISSUE THREAD

**Issue by alexjcollins** [verbb/gift-voucher#8]
### Description
I'm not sure if we're missing something but redemption logging doesn't appear to be working.

We're able to use a generated voucher fine at checkout, but once used it doesn't reduce the **Current Amount** value, therefore allowing it to be used multiple times. The redemptions UI also isn't showing on the Voucher Code page.

I noticed on the Craft 2 version, it was a block below the main details but there isn't anything like that on the Craft 3 version.
 
![screenshot 2018-12-05 at 16 05 09](https://user-images.githubusercontent.com/12031196/49526369-95b9aa80-f8a7-11e8-8fd3-968efe3787e9.png)

Not sure what further info we can send to help with debugging

(cc @Tam)

### Additional info

- Plugin version: 3.0.33
- Craft version: 2.0.4

**Comment by alexjcollins** [comment]
Hey @supportverbb, any news on this? Let me know if you need anything further from me - happy to send whatever over in order to help resolve.

**Comment by engram-design** [comment]
@alexjcollins Looks like this was an issue when the final amount of the order was $0, and the plugin wasn't therefore triggering redemption-handling which it should.

Fixed in [2.0.5](https://github.com/verbb/gift-voucher/releases/tag/2.0.5)

**Comment by engram-design** [comment]
See also https://github.com/craftcms/commerce/issues/600
