### ISSUE TITLE
Show vouchers in Product fields

### ISSUE THREAD

**Issue by pixelmachine** [verbb/gift-voucher#86]
I'm not sure if this is a limitation of Commerce or a UX choice but it would be great for vouchers to behave as first class products – since that's what they are.

They can't be selected alongside products in a Products field, they can't be returned with a single product query, they're outside of the Commerce section in the admin nav. It all leads to a messy setup for store managers and a lot of additional code if you want to integrate them.

If this is a Commerce issue then I'll repost over there.

**Comment by engram-design** [comment]
Yeah, not much we can do about this. Gift Vouchers are purchasable elements - a concept from Commerce, in that we provide a "thing" you can purchase. But it terms of it being completely separate to Commerce products, that's something they would need to address entirely on their end.

I suppose there are complexities with that, such as Gift Voucher (or [Event Tickets](https://github.com/verbb/events) which are also a custom purchasable), or Commerce Variants are all a little different, but they do share similarities. I imagine there would be complications is providing a seamless experience across these different types of content.

More importantly, I believe it's currently impossible to query across multiple element types.

**Comment by pixelmachine** [comment]
Thanks for confirming, I thought that might be the case.
