### ISSUE TITLE
Class "verbb\giftvoucher\services\Redemptions" not found

### ISSUE THREAD

**Issue by bymayo** [verbb/gift-voucher#88]
### Describe the bug

Trying to use the After Save Redemption event (https://verbb.io/craft-plugins/gift-voucher/docs/developers/events#the-afterSaveRedemption-event) but using the class brings back this error.

### Steps to reproduce

1. Add `use verbb\giftvoucher\services\Redemptions;` to file

### Craft CMS version

4.0.2

### Plugin version

3.0.0-beta.1

### Multi-site?

No

**Comment by engram-design** [comment]
Can you try [3.0.0-beta.2](https://github.com/verbb/gift-voucher/releases/tag/3.0.0-beta.2)? That class certainly exists, and it should for 3.0.0-beta.1 already

**Comment by bymayo** [comment]
It works after updating to 3.0.0-beta.2, strange it didn't work previously! Thanks!

**Comment by bymayo** [comment]
@engram-design Since updating though I get this error:

`verbb\giftvoucher\services\Redemptions::getRedemptionsByCodeId(): Return value must be of type array, craft\base\MemoizableArray returned`

Whenever I go to view a Voucher Code in the CMS

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/gift-voucher` requirement in `composer.json` to:

```
"require": {
  "verbb/gift-voucher": "dev-craft-4 as 3.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by bymayo** [comment]
Thanks! I'm also getting another redemption error which I noticed in the logs:

```
2022-07-14 11:00:20 [INFO] Adding 4 to code storage
2022-07-14 11:00:20 [ERROR] Unable to complete gift voucher order: “verbb\giftvoucher\services\Redemptions::_getRedemptionRecord(): Argument #1 ($id) must be of type string, null given, called in /Users/jasonmayo/Code/Github/@madebyshape/xxx/craft-cms/vendor/verbb/gift-voucher/src/services/Redemptions.php on line 63” /Users/jasonmayo/Code/Github/@madebyshape/xxx/craft-cms/vendor/verbb/gift-voucher/src/services/Redemptions.php:151
2022-07-14 11:00:20 [INFO] Request context:
$_GET = []

$_POST = [
    'CRAFT_CSRF_TOKEN' => '1KeZYO95SPBoI4XN-DCtz9eXLI9xsPmtwT-B_I1-0DdLyXc_g0di9pqyIHFdWorNQNFWKFmV48grl58GC0pTl9M3GAdfZUPJXZqdPeLX9MncHaZ_kMxtAiYUeVM9yzKpguU8P64WTl6ZkBkcyt6ZwPOzWJT8sQGQSwily5y_H3DYnndUTLKM59ixRLHpE5Vl1xU35tbhC6YJLJ4ZEsr5kWjcrua6Sbo61s7Etw7nnvQSlQEp-DJRxX8klOaERBNpObP4dONlHW6n0aoZpvo2MnJjoepVIT4-XHuobqiuC9XmkKu9eZYepfwJOh5yGmJc_gCQsNYNW5pwfGv6omhkoZfppJ3CadvI2FnhKjmIrqn0eUex6EYyLsvgou7TdfSHVa0jtWkF'
    'action' => 'commerce/payments/pay'
    'redirect' => 'e1f4bd9981a4c5698c19e3393aec7133986b7f5d925cc7d00bc0652023ba0074http://xxx.local/shop/customer/order?number=2216d98af443a3a14b0abd52a95642e9&success=true'
    'cancelUrl' => 'd0b6cf8db68d94340775094fec142f6e6540e03069bec3923db66c590c0fd2ffhttp://xxx.local/shop/checkout/payment'
    'orderEmail' => 'xxx@madebyshape.co.uk'
    'gatewayId' => '1'
    'paymentForm' => [
        'dummy' => [
            'firstName' => 'Jenny'
            'lastName' => 'Andrews'
            'number' => '4242424242424242'
            'expiry' => '01/2023'
            'cvv' => '123'
        ]
    ]
]
```

**Comment by engram-design** [comment]
Also updated (as you can tell I'm still working on things, also with some other Commerce changes!)

**Comment by bymayo** [comment]
@engram-design Thanks for the speedy fixes! Yeah I feel your pain, we're also hitting a few hiccups using Commerce 4, compared to how we did stuff in Commerce 3 in custom modules etc

**Comment by engram-design** [comment]
Should have everything finalised by the start of August at least, FYI.
