### ISSUE TITLE
Voucher codes not being generated

### ISSUE THREAD

**Issue by Tam** [verbb/gift-voucher#9]
### Description
The voucher codes are no longer being generated when an order is complete. The issue only seems to have started after updating to from commerce beta.13.1 to beta.14.

### Steps to reproduce

1. Add a voucher to your cart.
2. Checkout.

### Additional info

- Plugin version: 2.0.4
- Craft version: Craft Pro 3.0.34
- Commerce version: 2.0.0-beta.14

**Comment by Tam** [comment]
Ignore me, it is working but doesn't seem to work if you have a 100% test discount or when marking as complete without any payments.

**Comment by dowadidi** [comment]
Please reopen this issue. I have this issue on a live environment. Same plugin versions as above.

The voucher pdf is blank, and purchased vouchers do not appear in the backend.
