### ISSUE TITLE
Return value must be of type array, craft\base\MemoizableArray 

### ISSUE THREAD

**Issue by darinlarimore** [verbb/gift-voucher#92]
### Describe the bug

Craft throws TypeError: verbb\giftvoucher\services\Redemptions::getRedemptionsByCodeId(): Return value must be of type array, craft\base\MemoizableArray returned in .../vendor/verbb/gift-voucher/src/services/Redemptions.php:44

### Steps to reproduce

1. Open Voucher Codes section
2. Open a voucher code entry
3. TypeError is seen

### Craft CMS version

4.2.1.1

### Plugin version

3.0.0-beta.2

### Multi-site?

No

**Comment by engram-design** [comment]
See https://github.com/verbb/gift-voucher/pull/93#issuecomment-1226727252 sorry for the trouble, appreciate the PR!

**Comment by engram-design** [comment]
Fixed in [3.0.0](https://github.com/verbb/gift-voucher/releases/tag/3.0.0)
